# This is a TOML document.
# Config file for logreview-rs

# The web server log files to process.
filenames = [
  "log/test1.log",
  "log/test2.log"
]

# The number of top frequencies to display
number_of_frequencies = 10

# Column index to analyze (0-based)
column_index = 0
